export const categories = [
    "Theft",
  "Burglary",
  "Robbery",
  "Assault",
  "Harassment",
  "Domestic Violence",
  "Cybercrime",
  "Fraud",
  "Vandalism",
  "Drug-Related Crimes",
  "Human Trafficking",
  "Kidnapping",
  "Sexual Assault",
  "Homicide",
  "Arson",
  "Bribery & Corruption",
  "Stalking",
  "Hate Crime",
  "Traffic Violations",
  "Environmental Crimes",
  "Weapons Offenses",
  "Public Disturbance",
  "Animal Cruelty",
  "Identity Theft"
]